language: r
os: linux
cache: packages
warnings_are_errors: true
r_check_args: --as-cran --no-manual # Workaround error compiling PDF manual

git:
  depth: 1

r_binary_packages:
 - covr
 - devtools
 - Rcpp
 - roxygen2
 - testthat

r_github_packages:
 - ms609/TreeTools

before_script:
  - R -e "devtools::load_all(); devtools::document()"

jobs:
  include:
    - r: 3.4.0
    - r: release
      before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        skip-cleanup: true
    - r: devel
      branches:
        only: master
      after_success:
        - Rscript -e "covr::codecov()"
    - os: osx
      branches:
        only: master
      r: release
      r_packages:
        - ape
        - devtools
        - phangorn
        - Rcpp
        - roxygen2
        - testthat
      before_install:
      - brew install cairo
      - sudo tlmgr install doi titling hyperref
#  allow_failures:
