language: r
os: linux
cache: packages
warnings_are_errors: true
r_check_args: --as-cran --no-manual # Workaround error compiling PDF manual

git:
  depth: 1

r_binary_packages:
 - devtools
 - Rcpp
 - Rdpack
 - roxygen2
 - testthat

r_github_packages:
 - ms609/TreeDist

before_script:
  - R -e "devtools::load_all(); devtools::document()"

jobs:
  include:
    - r: 3.4.0
    - r: release
      r_packages:
        - pkgdown
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
    - r: devel
      r_binary_packages:
        - covr
      branches:
        only: master
      after_success:
        - Rscript -e "covr::codecov()"
    - os: osx
      branches:
        only: master
      r: release
      r_packages:
        - ape
        - devtools
        - phangorn
        - Rcpp
        - roxygen2
        - testthat
      before_install:
      - brew install cairo
      - sudo tlmgr install doi titling hyperref
#  allow_failures:
