language: r
os: linux
cache: packages
warnings_are_errors: true
r_check_args: --as-cran --no-manual # Workaround error compiling PDF manual

git:
  depth: 1

r_packages:
 - pkgload
 - devtools
 - testthat

before_script:
  - R -e "pkgload::load_all(); devtools::document()"

jobs:
  include:
    - r: 3.4.0
    - r: release
      r_binary_packages:
       - ape
       - devtools
       - Rcpp
       - Rdpack
       - phangorn
       - roxygen2
       - testthat
      r_packages:
        - pkgdown
      deploy:
        provider: script
        cleanup: false
        skip_cleanup: true
        script: Rscript -e 'pkgdown::deploy_site_github()'
    - r: devel
      r_binary_packages:
        - ape
        - covr
        - devtools
        - phangorn
        - Rcpp
        - Rdpack
        - roxygen2
        - testthat
      branches:
        only: master
      after_success:
        - Rscript -e "covr::codecov()"
    - os: osx
      branches:
        only: master
      r: release
      before_install:
      # - brew install cairo # Already installed
      - sudo tlmgr install doi titling hyperref
#  allow_failures:
