# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

r_uspr <- function(tree1, tree2, printMafs, countMafs, keepLabels, opt, protectB, tbrApprox, tbr, replug, uspr, approxEstimate, tbrEstimate, replugEstimate) {
    .Call('_uspr_r_uspr', PACKAGE = 'uspr', tree1, tree2, printMafs, countMafs, keepLabels, opt, protectB, tbrApprox, tbr, replug, uspr, approxEstimate, tbrEstimate, replugEstimate)
}

